name: Code Review
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reviewdog:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-setup@v1
        with:
          reporter: Cool Code Reviewer
          reviewdog_version: latest